### PR TITLE
Build better with scons

### PR DESCRIPTION
**Pull request by giorashh**
a-bit-early-and-not-precisely what was on @benswift 's [christmas list](https://github.com/digego/extempore/pull/158#issuecomment-67109544).

This is a stab at a fancier build system for extempore, based on the [scons](http://www.scons.org/) build tool, which uses Python as its underlying language. The provided build script:

- Provides help via 'scons help', specifically a list of valid targets.
- Checks EXT_LLVM_DIR or known homebrew locations for llvm.
- Checks llvm version.
- Checks that patches have been applied to 3d party libs (llvm) using md5 hashes.
- (Should) Support multiple platforms (Linux, OSX, Windows?).
- Compiles (and cleans) extempore binary.
- Compiles (and cleans) stdlib/stdlib-core/stdlib-external.
- Provides a target for running the tests.
- Allows compilation of specified stdlib files only. See 'scons help'
- Extracts dependency information from stdlib components (no parsing, just regexes).
- Supports parallel builds (with -j N) of stdlib, using dependency info to figure out compilation order.
- Caches all build artifacts (stdlib included).
- Supports command line flags (see --help for list, 'scons help' for example)

Choosing a build tool is invariably a contentious issue. All I can say is my experience with scons has been nothing but positive and the documentation has been top notch as well. I've looked at waf and CMake too and prefer scons better so far.

Tested on Fedora 21 and expect it to work out of the box on ubuntu. OSX should either work
or be relatively painless to get working.
Windows building should be possible, at least by converting the .bat files into scons' `env.Command`, but I haven't done it.

If you still want to hold out for CMake, I understand. This is a level-up on what the build system should be able to do.

### CODE REVIEW

**Comment by giorashh** [comment]
I get the feeling you have your heart set on CMAKE. fair enough.

**Comment by benswift** [comment]
Well, not necessarily.  I even rebased and did some work on it a few
days ago (which I haven't yet pushed to GH).  And also I was away over
Christmas and NY.

The big problem at the moment is that it doesn't work on OSX.  It's not
providing the `-framework` list to clang, and even though I tried the
scons `FRAMEWORKS` env var (as suggested by the docs) I couldn't get it
to work.  I wonder if it doesn't thing they're ObjC++ files since they
don't have a `.mm` extension.

So it's not that I've given up, but until it builds on OSX I really
can't merge it.

giorashh writes:

**Comment by giorashh** [comment]
That sounds fixable. If you'll push your fixes to the branch here I can try and find a solution (though I don't have a mac).

**Comment by benswift** [comment]
Ok, I've pushed up my latest changes to the scons-build branch (head
should be at e556d66).

Thanks for having a look.  I'm happy to have another crack at it when I
get a chance, but since I'm not a scons guy my progress is slow.

giorashh writes:

**Comment by giorashh** [comment]
I'll give it a go (new to scons myself and macless, but hey). I don't see any new commits related to scons in your push though. Is there anything after 4946540 you meant to include?

**Comment by giorashh** [comment]
scons considers FRAMEWORKS to be a *link-time* flag so omits it when compiling to objects. I do see the `-frameworks foo etc' added when the `extempore` binary is linked as a last step and that all seems as it should be. I'm not familiar with dev on OSX so tell me if I'm missing something.

**Comment by benswift** [comment]
Just an update on this one:  I asked on [SO](http://stackoverflow.com/questions/28160913/scons-and-objc) about this, it turns out that scons can't do this at the moment, and since I don't have the time to add the support to scons then I think that option is a dead end for the moment.

Thanks for trying.

**Pull request closed without merging**
