### PR TITLE
Add some scales

### PR DESCRIPTION
**Pull request by cyblue9**
Hi!

I added some scales.

REF:[List of musical scales and modes](https://en.wikipedia.org/wiki/List_of_musical_scales_and_modes)

- Question
Above page explains major pentatonic scale and minor pentatonic scale.
So, I want to add minor pentatonic scale.
Therefore, May I change Existing `pentatonic` variable to `^pentatonic` variable? (and 
I am going to add `-pentatonic` variable.)
 

Please review!

### CODE REVIEW

**Comment by benswift** [comment]
Fine with me, but I'll just check with @digego re: naming conventions - do you want them, and what do you want them to be called?

**Comment by digego** [comment]
Hi, thanks for updates!

I think that we should maintain the 'major pentatonic' as simply 'pentatonic' and then add the minor pentatonic as 'pentatonic-minor'.   I don't really think of pentatonic as both major and minor.  I think of it as simply pentatonic, and some people like to 'construct' a minor variant.

I'm also unsure about what ^melodic and -melodic are supposed to be?  Melodic minor I'm guessing, but I'm unsure how these are supposed to translate, and how useful they are?  Don't we just want (melodic .  (2 1 2 2 2 2))?   The 'downward' trajectory is simply aeolian?

just my 2cents

**Comment by cyblue9** [comment]
Thanks to reply!

> I think that we should maintain the 'major pentatonic' as simply 'pentatonic' and then add the minor pentatonic as 'pentatonic-minor'. I don't really think of pentatonic as both major and minor. I think of it as simply pentatonic, and some people like to 'construct' a minor variant.

Since no other scale minor variants are defined, it may not be necessary to define a pentatonic minor variant as well.
I will delete this.

> I'm also unsure about what ^melodic and -melodic are supposed to be? Melodic minor I'm guessing, but I'm unsure how these are supposed to translate, and how useful they are? Don't we just want (melodic . (2 1 2 2 2 2))? The 'downward' trajectory is simply aeolian?

Oh, I see. I did not understand the melody scale well.
You are right.
I will fix to define `(melody (2 1 2 2 2 2))` only.

**Comment by cyblue9** [comment]
Please Re-review!

**Comment by cyblue9** [comment]
Ping... @digego

**Comment by cyblue9** [comment]
Thank you very much! 😀

**Pull request merged**
